version: '3.3'

services:
  backend_api:
    container_name: backend_api
    restart: unless-stopped
    build: 
      dockerfile: ./dockerfile
      context: .
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - "${PORT}:${PORT}"
    command: sh -c "npm run migrate && npm run dev"
    depends_on:
      backend_db:
        condition: service_started
    links:
      - backend_db
  backend_db:
    image: postgres:13.6-alpine
    container_name: backend_db
    restart: unless-stopped
    volumes:
      - ./docker/postgres_db/db_data:/var/lib/postgresql
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
volumes:
  node_modules:  